### ISSUE TITLE
[Feat] 프론트엔드 공통 컴포넌트 생성 및 초기 세팅

### ISSUE THREAD

**Issue by leejin-rho** [Ureca-6-PawSeul/PawSeul#1]
### 기능 개요

프론트엔드 공통 컴포넌트 생성 및 초기 세팅

### TODO

- [x] 리액트 초기 세팅
- [x] 스토리북 설치
- [x] Navbar 생성 및 구현
- [x] 기본 component 생성 및 구현
- [x] 폰트, 색상 설정
