### ISSUE TITLE
[Feat] 상품 상세 페이지 UI 구현

### ISSUE THREAD

**Issue by ongheong** [Ureca-6-PawSeul/PawSeul#17]
### 기능 개요

상품 상세 페이지 UI 구현

### TODO

- [x] mock 데이터로 상세 페이지 레이아웃 구현
- [x] 기존 star 컴포넌트로 별점 UI 추가
- [x] 상품 설명 더보기 기능 구현
- [ ] 후기 레이아웃 구현
- [ ] 후기 컴포넌트 구현
