### ISSUE TITLE
[Feat] 벡엔드 초기 설정

### ISSUE THREAD

**Issue by Hellol77** [Ureca-6-PawSeul/PawSeul#2]
### 기능 개요

벡엔드 초기 설정을 위한 이슈입니다. 각종 라이브러리 설치와 mysql 설정이 들어가 있습니다.

### TODO

- [x] nest.js 초기 설정
- [x] 라이브러리 설치
- [x] mysql 설치 및 연동
- [x] cookie parser 설치
- [x] github action을 사용한 벡엔드 배포
